#-------------------------------
# General Site Settings
title: Marcelo Paiva
logo: logo.svg # You can add own logo.
description: A site about my failures and successes that just happen to inspire people I meet along the way.


#-------------------------------
# Author Settings
author:
  name: Marcelo Paiva
  image: 01.jpg
  say-hello: ðŸ‘‹ Iâ€™m <strong>Marcelo Paiva</strong>
  bio: Learning something new every day is my school. Sharing what I learn with the community is my joy. Building cross-functional teams is my passion. Designing with Accessibility in mind is focal point. Practicing Inclusive Design is my beacon.


#-------------------------------
# Contact links
twitter: https://twitter.com/muqueca # Add your Twitter handle
github: https://github.com/mpaiva # Add your Github handle
dribbble: https://dribbble.com/mpaiva # Add your Dribbble handle
linkedin: https://www.linkedin.com/in/mtpaiva/ # Add your LinkedIn handle
# pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mpaiva # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: mpaiva_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
